# Server configuration
server.port=${SERVER_PORT:8089}

# name local
spring.application.name=${SPRING_APPLICATION_NAME:PRODUCT-SERVICE}

# postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://product-db:5432/productservice}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vdv32514}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}