# Server configuration
server.port=${SERVER_PORT:8088}
spring.application.name=${SPRING_APPLICATION_NAME:USER-SERVICE}

# Database Configuration
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/userservice}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vdv32514}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# JWT Configuration
jwt.secret=${JWT_SECRET:WX5pJ7vQ2zTbV9yN1cR4fU6iM8kL3oP5hA0qS9dF2gH7jK4lZ1xW8eB5vC6mD3nG}
jwt.expiration=${JWT_EXPIRATION:86400}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:172800}

# Kafka Configuration
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.retries=${SPRING_KAFKA_PRODUCER_RETRIES:3}
spring.kafka.producer.batch-size=${SPRING_KAFKA_PRODUCER_BATCH_SIZE:16384}
spring.kafka.producer.buffer-memory=${SPRING_KAFKA_PRODUCER_BUFFER_MEMORY:32MB}

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}

# Refresh Token Configuration
refresh.token.url=${REFRESH_TOKEN_URL:http://api-gateway:8080/api/auth/refresh}