spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dedgove@gmail.com
    password: mbcs kjse ikaa yryt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true