# Server configuration
server.port=8084

# name local
spring.application.name=ORDER-SERVICE

# postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/productservice
spring.datasource.username=postgres
spring.datasource.password=vdv32514
spring.jpa.hibernate.ddl-auto=update

# secret and expiration
jwt.secret=WX5pJ7vQ2zTbV9yN1cR4fU6iM8kL3oP5hA0qS9dF2gH7jK4lZ1xW8eB5vC6mD3nG
jwt.expiration=86400

# eureka server url
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher