# Server configuration
server.port=${SERVER_PORT:8084}

# Application name
spring.application.name=${SPRING_APPLICATION_NAME:ORDER-SERVICE}

# R2DBC Configuration
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://order-db:5432/orderservice}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:vdv32514}
spring.r2dbc.schema=${SPRING_R2DBC_SCHEMA:schema.sql}

# Service URLs
services.user.url=${USER_SERVICE_URL:http://localhost:8088}
services.product.url=${PRODUCT_SERVICE_URL:http://localhost:8086}

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:dedgove@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mbcs_kjse_ikaa_yryt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=${JWT_SECRET:WX5pJ7vQ2zTbV9yN1cR4fU6iM8kL3oP5hA0qS9dF2gH7jK4lZ1xW8eB5vC6mD3nG}
jwt.expiration=${JWT_EXPIRATION:86400}

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# Swagger
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Logging
logging.level.org.nicetu.spb.orderservice=DEBUG
logging.level.org.springframework.data.r2dbc=INFO
logging.level.org.springframework.transaction=DEBUG