# Server configuration
server.port=${SERVER_PORT:8084}

# name local
spring.application.name=${SPRING_APPLICATION_NAME:ORDER-SERVICE}

# postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://order-db:5432/orderservice}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vdv32514}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:dedgove@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mbcs_kjse_ikaa_yryt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# secret and expiration
jwt.secret=${JWT_SECRET:WX5pJ7vQ2zTbV9yN1cR4fU6iM8kL3oP5hA0qS9dF2gH7jK4lZ1xW8eB5vC6mD3nG}
jwt.expiration=${JWT_EXPIRATION:86400}

# eureka server url
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# swagger-ui custom path
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher