#Server port :
server.port=8082

#Application name :
spring.application.name=INVENTORY-SERVICE

# postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryservice
spring.datasource.username=postgres
spring.datasource.password=vdv32514
spring.jpa.hibernate.ddl-auto=update

# Eureka server url
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

# Secret key
jwt.secret-key=vip2023

# localhost user-service
user-service.base-url=http://localhost:8080